import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import PrismaticBurst from "@/components/PrismaticBurst";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable}  ${geistMono.variable} antialiased selection:bg-black/10 dark`}
      >
        <Navbar />
        <div className="fixed inset-0 -z-20 bg-background" />
        <div className="fixed inset-0 -z-10">
          <PrismaticBurst
            animationType="rotate3d"
            intensity={4}
            speed={0.25}
            paused={false}
            offset={{ x: 0, y: 0 }}
            hoverDampness={0.25}
            mixBlendMode="lighten"
          />
        </div>
        <div className="relative z-10 min-h-screen">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
